export const GET_OLYMPICS_ALL = 'GET_OLYMPICS_ALL';
export const GET_YEARS_ALL = 'GET_YEARS_ALL';
export const GET_OLYMPICS_BY_YEAR = 'GET_OLYMPICS_BY_YEAR';
export const GET_OLYMPICS_BY_TEAM = 'GET_OLYMPICS_BY_TEAM';
export const CLEAR_OLYMPICS_FILTERED = 'CLEAR_OLYMPICS_FILTERED';
export const GET_TEAM_MEDAL_ROLLUP = 'GET_TEAM_MEDAL_ROLLUP';
export const GET_TEAM_MEDAL_ROLLUP_BY_GENDER =
	'GET_TEAM_MEDAL_ROLLUP_BY_GENDER';
export const GET_TEAM_MEDAL_ROLLUP_BY_YEAR = 'GET_TEAM_MEDAL_ROLLUP_BY_YEAR';
